### PR TITLE
Fix asset to work with Teraslice versions lower than v1.4.0

### PR DESCRIPTION
**Pull request by sotojn**
This PR makes the following changes:

- Introduces backwards compatibility for teraslice versions before `v1.4.0`
  - This fixes an issue where using a teraslice version older than version `v1.4.0` would throw `TypeError: this.promMetrics.addGauge is not a function`
- Bump **kafka-assets** to `v4.4.1`
- Updates the following dependencies:
  - **@terascope/job-components** from `v0.74.2` to `v0.75.0`

ref: https://github.com/terascope/teraslice/issues/3625

### CODE REVIEW

**Review by godber — APPROVED** [review]
Looks good!
So far, I like this method better than the proxy.  It reads well and makes sense in the scenarios we've implemented it.
